name: msxvr image builder
on:
  push:
    tags:
      - 'v*'
jobs:
  make-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        DISTRO: ["raspios"]
        SUITE: ["buster"]
        ARCH: ["armhf"]
        VARIANT: ["lite"]
    name: msxvr-builder
    steps:
      - uses: actions/checkout@v2
      - name: Build images
        run: |
              sudo ARCHITECTURE=${{ matrix.ARCH }} ./msxvr-builder.sh
              sha256sum ${{ matrix.DISTRO }}-${{ matrix.SUITE }}-${{ matrix.VARIANT }}-${{ matrix.ARCH }}.img.xz \
                > ${{ matrix.DISTRO }}-${{ matrix.SUITE }}-${{ matrix.VARIANT }}-${{ matrix.ARCH }}.img.sha256
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.vars.outputs.tag }}
          draft: false
          files: ${{ matrix.DISTRO }}-${{ matrix.SUITE }}-${{ matrix.VARIANT }}-${{ matrix.ARCH }}.img.*
